/* Cliente: sonido y animación. El resultado final se calcula exclusivamente en backend. */
const $ = s => document.querySelector(s);
let gameId, rounds, round = 0, locked = false, audio, oscillators = [], sampleVoice, timer, started, results = [];
const screens = ['intro','game','result'];
function show(name){ screens.forEach(x => $('#'+x).classList.toggle('active',x===name)); }
function centsToHz(base,cents){ return base * Math.pow(2,cents/1200); }
async function startVoice(){
  // Si el estudio añade audio/ah-loop.mp3, se prioriza la voz humana.
  try { const probe = await fetch('/audio/ah-loop.mp3', { method: 'HEAD' }); if (probe.ok) { sampleVoice = new Audio('/audio/ah-loop.mp3'); sampleVoice.loop = true; sampleVoice.volume = .7; sampleVoice.preservesPitch = false; sampleVoice.mozPreservesPitch = false; sampleVoice.webkitPreservesPitch = false; await sampleVoice.play(); return; } } catch (_) { /* sintetizador de respaldo */ }
  audio = new (window.AudioContext || window.webkitAudioContext)();
  // Dos osciladores y filtros formantes: vocal Ah ligera, sin descargar recursos pesados.
  const gain=audio.createGain(); gain.gain.value=.0001; gain.connect(audio.destination);
  [1,2].forEach((harmonic,i)=>{const osc=audio.createOscillator(), f=audio.createBiquadFilter();osc.type=i?'triangle':'sawtooth';osc.frequency.value=220*harmonic;f.type='bandpass';f.frequency.value=i?1100:700;f.Q.value=5;osc.connect(f).connect(gain);osc.start();oscillators.push(osc);});
  gain.gain.exponentialRampToValueAtTime(.065,audio.currentTime+.12); audio.voiceGain=gain;
}
function updateSound(){ const hz=centsToHz(rounds[round].hz,+$('#pitch').value); if(sampleVoice){ sampleVoice.playbackRate=hz/440; return; } if(!audio)return; oscillators.forEach((o,i)=>o.frequency.setTargetAtTime(hz*(i+1),audio.currentTime,.025)); }
function updatePitch(){const c=+$('#pitch').value, margin=rounds[round].margin;$('#cents').textContent=`${c>0?'+':''}${c}¢`;$('#needle').style.left=`${(c+500)/10}%`;const on=Math.abs(c)<=margin;$('#state').textContent=on?'EN EL PUNTO':'ENCUENTRA EL TONO';$('#state').style.color=on?'#7dffbb':'';$('#lock').disabled=!on;updateSound();}
function loadRound(){ locked=false; const r=rounds[round], offset=Math.round((Math.random()>.5?1:-1)*(160+Math.random()*240));$('#pitch').value=offset;$('#note').textContent=r.note;$('#hz').textContent=`${r.hz.toFixed(2)} HZ`;$('#round').innerHTML=`${String(round+1).padStart(2,'0')} <i>/ 10</i>`;$('#progress').style.width=`${round*10}%`;$('#lock').disabled=true;updatePitch(); }
function tick(){const remain=Math.max(0,45-(performance.now()-started)/1000);$('#time').textContent=remain.toFixed(1);if(!remain){clearInterval(timer);finish();}}
async function begin(){try{const r=await fetch('/api/game/start',{method:'POST'});const data=await r.json();if(!r.ok)throw Error(data.error);gameId=data.gameId;rounds=data.rounds;round=0;results=[];show('game');await startVoice();started=performance.now();timer=setInterval(tick,50);loadRound();}catch(e){alert(e.message||'No fue posible iniciar el reto.');}}
async function lockRound(){if(locked)return;locked=true;$('#lock').disabled=true;try{const r=await fetch('/api/game/round',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId,cents:+$('#pitch').value})}),data=await r.json();if(!r.ok)throw Error(data.error);results.push(data.precision);$('#accuracy').textContent=`${Math.round(results.reduce((a,b)=>a+b,0)/results.length)}%`;$('#state').textContent=data.correct?'¡AFINADO!':'CASI';$('#state').style.color=data.correct?'#7dffbb':'#ff6b7d';setTimeout(()=>{round++;if(round===10)finish();else loadRound();},430);}catch(e){alert(e.message);finish();}}
async function finish(){clearInterval(timer);if(sampleVoice){sampleVoice.pause();sampleVoice=null}if(audio){audio.voiceGain.gain.setTargetAtTime(.0001,audio.currentTime,.03);setTimeout(()=>audio.close(),200);audio=null;oscillators=[]}try{const r=await fetch('/api/game/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId})}),data=await r.json();show('result');$('#finalScore').textContent=`${data.accuracy||0}%`;$('#resultTitle').textContent=data.won?'Lo lograste.':'Sigue afinando.';$('#resultOverline').textContent=data.won?'RETO SUPERADO':'RETO FINALIZADO';$('#resultText').textContent=data.won?'Completaste las 10 rondas con la precisión necesaria. Tu recompensa está lista.':'Necesitas completar las 10 rondas con al menos 90% de precisión. Vuelve a intentarlo.';$('#claim').classList.toggle('hidden',!data.won);$('#codeBox').classList.add('hidden');}catch{show('result');$('#resultTitle').textContent='Tiempo terminado.';$('#resultText').textContent='El reto debe completarse en 45 segundos.';$('#claim').classList.add('hidden');}}
$('#start').onclick=begin;$('#pitch').oninput=updatePitch;$('#lock').onclick=lockRound;$('#again').onclick=()=>show('intro');
$('#claimForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const r=await fetch('/api/prize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId,name:$('#name').value,email:$('#email').value})}),d=await r.json();if(!r.ok)throw Error(d.error);$('#code').textContent=d.code;$('#claim').classList.add('hidden');$('#codeBox').classList.remove('hidden');}catch(err){alert(err.message)}finally{b.disabled=false}};
