/* API segura del reto: el navegador no puede declarar puntajes ni victorias. */
const express=require('express'),crypto=require('crypto'),path=require('path'),store=require('./store');require('dotenv').config();
const app=express(),root=path.join(__dirname,'..'),port=+process.env.PORT||3000,adminUser=process.env.ADMIN_USER||'admin',adminPassword=process.env.ADMIN_PASSWORD||'cambia-esto';
const games=new Map(),now=()=>new Date().toISOString(),ip=req=>(req.ip||'').slice(0,64),id=()=>crypto.randomBytes(18).toString('base64url');
const notes=[['C5',523.25],['D5',587.33],['E5',659.25],['F5',698.46],['G5',783.99],['A5',880],['B5',987.77]].map(([name,hz])=>({name,hz}));
app.set('trust proxy',1);app.use(express.json({limit:'12kb'}));app.use(express.static(root,{index:'index.html'}));
function auth(req,res,next){const h=req.headers.authorization||'',ok=h.startsWith('Basic ')&&Buffer.from(h.slice(6),'base64').toString()===`${adminUser}:${adminPassword}`;if(!ok){res.set('WWW-Authenticate','Basic realm="Sonder Admin"');return res.status(401).send('Acceso restringido');}next();}
function makeCode(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c='SONDER-';for(let i=0;i<5;i++)c+=a[crypto.randomInt(a.length)];return c;}
app.post('/api/game/start',(req,res)=>{const address=ip(req),since=new Date(Date.now()-864e5).toISOString(),maxAttempts=process.env.NODE_ENV==='production'?3:99;if(store.attempts(address,since)>=maxAttempts)return res.status(429).json({error:'Has alcanzado el máximo de 3 intentos por hoy. Vuelve mañana.'});const rounds=Array.from({length:10},(_,i)=>({note:notes[crypto.randomInt(i<3?3:notes.length)],margin:i<3?180:Math.max(105,165-i*8)}));const game={id:id(),ip:address,started:Date.now(),rounds,current:0,results:[]};games.set(game.id,game);store.addPlay({id:game.id,ip:address,created_at:now(),rounds:0,correct_rounds:0,average_precision:0,status:'active'});res.json({gameId:game.id,rounds:rounds.map(r=>({note:r.note.name,hz:r.note.hz,margin:r.margin})),duration:45});});
app.post('/api/game/round',(req,res)=>{const g=games.get(req.body.gameId),c=Number(req.body.cents);if(!g||g.ip!==ip(req)||!Number.isFinite(c))return res.status(400).json({error:'Partida no válida.'});if(g.current>=10||Date.now()-g.started>45000)return res.status(400).json({error:'El tiempo de juego terminó.'});const r=g.rounds[g.current],precision=Math.max(0,100-Math.abs(c)/r.margin*20),correct=Math.abs(c)<=r.margin;g.results.push({precision,correct});g.current++;res.json({correct,precision:Math.round(precision),completed:g.current,finished:g.current===10});});
app.post('/api/game/finish',(req,res)=>{const g=games.get(req.body.gameId);if(!g||g.ip!==ip(req)||g.current!==10)return res.status(400).json({error:'Partida incompleta.'});const avg=g.results.reduce((s,x)=>s+x.precision,0)/10,won=Date.now()-g.started<=45000&&avg>=90&&g.results.every(x=>x.correct);store.updatePlay(g.id,{completed_at:now(),rounds:10,correct_rounds:g.results.filter(x=>x.correct).length,average_precision:avg,status:won?'winner':'finished'});g.won=won;g.finished=Date.now();res.json({won,accuracy:Math.round(avg)});});
app.post('/api/prize',(req,res)=>{const g=games.get(req.body.gameId),name=String(req.body.name||'').trim().slice(0,100),email=String(req.body.email||'').trim().toLowerCase().slice(0,254);if(!g||g.ip!==ip(req)||!g.won||Date.now()-g.finished>9e5)return res.status(403).json({error:'Premio no disponible para esta partida.'});if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:'Ingresa un nombre y correo válidos.'});if(store.emailExists(email))return res.status(409).json({error:'Este correo ya recibió un código.'});let code;do{code=makeCode()}while(store.codeExists(code));store.addCode({code,name,email,created_at:now(),used_at:null,redeemed:0,ip:g.ip,user_agent:String(req.headers['user-agent']||'').slice(0,500),source:'game'});games.delete(g.id);res.json({code});});
app.get('/api/admin/stats',auth,(req,res)=>{const s=store.stats();res.json({...s,winRate:s.plays?Math.round(s.winners/s.plays*100):0});});app.get('/api/admin/codes',auth,(req,res)=>res.json(store.codes()));
app.post('/api/admin/codes',auth,(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),name=String(req.body.name||'Manual').trim().slice(0,100);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:'Correo no válido.'});if(store.emailExists(email))return res.status(409).json({error:'Ese correo ya tiene código.'});let code;do{code=makeCode()}while(store.codeExists(code));store.addCode({code,name,email,created_at:now(),used_at:null,redeemed:0,ip:'admin',user_agent:'admin',source:'manual'});res.json({code});});
app.post('/api/admin/codes/:id/redeem',auth,(req,res)=>store.redeem(req.params.id,now())?res.json({ok:true}):res.status(404).json({error:'Código no disponible.'}));
app.get('/api/admin/export.csv',auth,(req,res)=>{const rows=store.codes(),keys=['code','name','email','created_at','used_at','redeemed','ip','user_agent','source'],esc=v=>`"${String(v??'').replaceAll('"','""')}"`;res.type('text/csv').attachment('sonder-codes.csv').send([keys.join(','),...rows.map(x=>keys.map(k=>esc(x[k])).join(','))].join('\n'));});
app.get('/admin',(req,res)=>res.sendFile(path.join(root,'admin.html')));app.listen(port,()=>console.log(`Sonder Music listo en puerto ${port}`));
